0mad/yolobook

- frontend/.babelrc
- frontend/components/common/Header/Header.scss
- frontend/package-lock.json
- frontend/package.json
- frontend/pages/index.tsx
- frontend/styles/utils/_variables.scss
- frontend/tsconfig.json
- frontend/utils/withSizes.ts
- ts와 scss에서 768px를 기준으로 데스크탑모드와 모바일 모드를 체크할 수 있도록 처리
- 추후에 mobx를 사용할 수 있도록 환경 설정
> #17 반응형 웹 적용

- frontend/components/common/Button/Button.scss
- frontend/components/common/Button/Button.tsx
- frontend/components/common/Button/index.ts
- frontend/pages/anatomy.tsx
- frontend/styles/base.scss
- base.scss 컨밴션 수정
- 공통으로 재사용해서 사용할 수 있는 버튼 컴포넌트 추가
- 버튼 사용법을 공유하기 위해 임시 anatomy 페이지 생성
> #10 공통 컴포넌트 개발 - Button

- .gitignore
- frontend/.storybook/addons.js
- frontend/.storybook/config.js
- frontend/.storybook/webpack.config.js
- frontend/components/common/Button/Button.stories.tsx
- frontend/components/common/Header/Header.stories.tsx
- frontend/package-lock.json
- frontend/package.json
- 스토리북 환경 설정
- Button, Header 스토리 추가
- .gitignore 추가 : storybook build output
> #21 스토리북 사용환경 구성

- frontend/components/Editor/Editor.scss
- frontend/components/Editor/Editor.stories.tsx
- frontend/components/Editor/Editor.tsx
- frontend/components/Editor/index.tsx
- frontend/components/common/Button/Button.scss
> #27 컴포넌트 - 포스트 작성

- frontend/components/Viewer/Viewer.scss
- frontend/components/Viewer/Viewer.stories.tsx
- frontend/components/Viewer/Viewer.tsx
- frontend/components/Viewer/index.tsx
> #29 컴포넌트 - 뷰어

- frontend/components/Banner/Banner.scss
- frontend/components/Banner/Banner.stories.tsx
- frontend/components/Banner/Banner.tsx
- frontend/components/Banner/index.ts
> #31 컴포넌트 - 배너

- frontend/package.json
- frontend/server.js
- 개발 서버를 띄울시 frontend에 proxy 설정이 되어 있어야하므로 환경 설정
> #42 frontend proxy 설정

- frontend/.storybook/webpack.config.js
- frontend/components/Login/Login.scss
- frontend/components/Login/Login.stories.tsx
- frontend/components/Login/Login.tsx
- frontend/components/Login/LoginButton.scss
- frontend/components/Login/LoginFooter.scss
- frontend/components/Login/LoginFooter.tsx
- frontend/components/Login/LoginHeader.scss
- frontend/components/Login/LoginHeader.tsx
- frontend/components/Login/LoginTemplate.scss
- frontend/components/common/Header/Header.scss
- frontend/components/common/Header/Header.stories.tsx
- frontend/components/common/Header/Header.tsx
- frontend/components/common/PageTemplate/PageTemplate.scss
- storybook > webpack > css-loader 에 localIdentName 옵션 추가
- LoginHeader 별도로 생성
> #41 컴포넌트 - 둘러보기 헤더

- frontend/components/Post/Post.scss
- frontend/components/Post/Post.stories.tsx
- frontend/components/Post/Post.tsx
- frontend/components/Post/PostGallery.scss
- frontend/components/Post/PostGallery.tsx
- frontend/components/Post/index.ts
> #26 컴포넌트 - 포스트

- frontend/.storybook/config.js
- frontend/components/Gallery/Gallery.scss
- frontend/components/Gallery/Gallery.stories.tsx
- frontend/components/Gallery/Gallery.tsx
- frontend/components/Gallery/GalleryPhoto.scss
- frontend/components/Gallery/GalleryPhoto.tsx
- 갤러리 컴포넌트 작성
- storybook의 배경 색을 기본으로 회색으로 변경
> #25 컴포넌트 - 갤러리

- frontend/components/Login/Login.scss
- frontend/components/Login/LoginFooter.scss
- frontend/components/Login/LoginFooter.tsx
- frontend/components/Login/LoginHeader.tsx
- frontend/components/Login/LoginTemplate.scss
- frontend/components/Login/LoginTemplate.tsx
- frontend/components/Login/index.ts
- frontend/components/common/Header/Header.scss
- frontend/next.config.js
- frontend/package.json
- frontend/pages/login.tsx
- next-images 모듈 적용
- 로그인 페이지  작성
> #24 로그인 페이지

- frontend/components/Banner/Banner.tsx
- frontend/components/common/ContentLayout/ContentLayout.scss
- frontend/components/common/ContentLayout/ContentLayout.tsx
- frontend/components/common/ContentLayout/index.ts
- frontend/containers/BannerContainer.tsx
- frontend/containers/UserInfoContainer.tsx
- frontend/pages/profile/info.tsx
- frontend/routes.js
- 사용자 정보 페이지 조립
- Banner 컴포넌트에서 classname을 염두하지 않고 queryselector로 dom 접근을 해서 요소 스타일 수정을 재대로 하지 못해 ref로 수정
> #12 사용자 정보 페이지 - 소개

- frontend/components/Friend/Friend.scss
- frontend/components/Friend/Friend.stories.tsx
- frontend/components/Friend/Friend.tsx
- frontend/components/Friend/FriendItem.scss
- frontend/components/Friend/FriendItem.tsx
- frontend/components/Friend/index.ts
- frontend/components/common/Button/Button.scss
> #28 컴포넌트 - 친구

- frontend/components/PostWrapper/PostWrapper.tsx
- frontend/components/PostWrapper/index.ts
- frontend/components/common/Header/Header.scss
- frontend/components/common/PageTemplate/PageTemplate.scss
- frontend/containers/EditorContainer.tsx
- frontend/containers/PostContainer.tsx
- frontend/pages/_app.tsx
- frontend/pages/timeline.tsx
- frontend/routes.js
- PostWrapper에 PostEditor 제외
- PostEditorContainer, PostWrapperContainer 생성
> #9 타임라인 페이지

- frontend/components/Banner/Banner.tsx
- frontend/components/Friend/Friend.scss
- frontend/components/Friend/Friend.stories.tsx
- frontend/components/Friend/Friend.tsx
- frontend/components/Friend/FriendItem.scss
- frontend/components/Friend/FriendItem.tsx
- frontend/components/Friend/index.ts
- frontend/components/Gallery/Gallery.tsx
- frontend/components/Gallery/GalleryPhoto.tsx
- frontend/components/Gallery/index.ts
- frontend/components/PostWrapper/PostWrapper.tsx
- frontend/components/PostWrapper/index.ts
- frontend/components/common/Button/Button.scss
- frontend/components/common/Header/Header.scss
- frontend/components/common/PageTemplate/PageTemplate.scss
- frontend/containers/EditorContainer.tsx
- frontend/containers/PictureContainer.tsx
- frontend/containers/PostContainer.tsx
- frontend/pages/_app.tsx
- frontend/pages/profile/picture.tsx
- frontend/pages/timeline.tsx
- frontend/routes.js
> #14 사용자 정보 페이지 - 사진

- frontend/components/Friend/Friend.scss
- frontend/components/Friend/Friend.stories.tsx
- frontend/components/Friend/Friend.tsx
- frontend/components/Friend/FriendItem.scss
- frontend/components/Friend/FriendList.scss
- frontend/components/Friend/FriendList.tsx
> #57 컴포넌트 - 친구 목록

- frontend/components/Banner/Banner.tsx
- frontend/components/Friend/index.ts
- frontend/containers/FriendContainer.tsx
- frontend/pages/profile/friend.tsx
- frontend/routes.js
- frontend/styles/base.scss
> #13 사용자 정보 페이지 - 친구

- frontend/components/Friend/Friend.stories.tsx
- frontend/components/Friend/FriendRequest.scss
- frontend/components/Friend/FriendRequest.tsx
> #55 컴포넌트 친구 요청

- backend/.env
- backend/.gitignore
- backend/.prettierrc.js
- backend/package-lock.json
- backend/package.json
- backend/src/app.ts
- backend/src/config/index.js
- backend/src/lib/crypto.ts
- backend/src/lib/token.ts
- backend/src/logger.ts
- backend/src/models/Account.ts
- backend/src/routes/auth/auth.controller.ts
- backend/src/routes/auth/index.ts
- backend/src/routes/auth/ref.auth.controller.ts
- backend/src/routes/index.ts
- backend/src/routes/post/index.ts
- backend/src/routes/post/post.controller.ts
- backend/src/routes/user/index.ts
- backend/src/routes/user/user.controller.ts
- backend/src/sequelize.ts
- backend/tsconfig.json
- backend/tslint.json
- frontend/package.json
- express 프레임워크 사용
- 프로젝트 구조 잡기
- mysql, sequlize 사용
- typescript 적용
> #22 백엔드 개발환경 구축

- frontend/containers/LoginContainer.tsx
- frontend/next.config.js
- frontend/package.json
- frontend/pages/_app.tsx
- frontend/styles/base.scss
- toastify 컨테이너 설정
- toastify 관련 css는 로컬화 제외하도록 설정
> #74 toastify 모듈 셋팅

- backend/src/app.ts
- backend/src/models/Account.ts
- backend/src/models/Follow.ts
- backend/src/routes/follow/follow.controller.ts
- backend/src/routes/follow/index.ts
- backend/src/routes/index.ts
- backend/src/routes/user/index.ts
- backend/src/routes/user/user.controller.ts
- frontend/api/follow.ts
- frontend/api/user.ts
- frontend/components/Banner/Banner.scss
- frontend/components/Banner/Banner.tsx
- frontend/components/Follow/Follow.stories.tsx
- frontend/components/Follow/Follow.tsx
- frontend/components/common/Header/Header.tsx
- frontend/containers/BannerContainer.tsx
- frontend/containers/FollowContainer.tsx
- frontend/routes.js
- frontend/stores/modules/FollowStore.ts
- frontend/stores/modules/index.ts
- frontend/tslint.json
- 친구 요청 버튼 생성
- 요청 받은, 요청한 리스트 페이지 생성
- 요청 수락, 거절, 요청 취소 구현
- tslint member-order false 셋팅
> #81 친구 요청 기능

- backend/src/routes/follow/follow.controller.ts
- frontend/containers/FollowContainer.tsx
- frontend/stores/modules/FollowStore.ts
- FollowList를 서버로 부터 Follower, Following 으로 구분 해서 보내도록 수정
- 클라이언트에서 FollowerList, Following 리스트 구분해서 처리하도록 수정
> #101 FollowStore 개선

- frontend/components/Login/LoginNaver.tsx
- frontend/containers/BeforeMountComponent.tsx
- frontend/server.js
- 서버 프록시 설정 변경
- 네이버 로그인 팝업동작 셋팅
- 네이버 로그인 시도 횟수 제한
- /login 페이지에서는 1초후 리다이렉트 되도록 처리
> #119 배포 환경에서 네이버 로그인 버그

- backend/src/models/Post.ts
- frontend/components/Post/Post.scss
- frontend/components/Post/Post.stories.tsx
- frontend/components/Post/Post.tsx
- frontend/components/Post/PostGallery.scss
- frontend/components/Post/PostGallery.tsx
- frontend/components/PostWrapper/PostWrapper.tsx
- frontend/components/Viewer/Viewer.scss
- frontend/components/Viewer/Viewer.tsx
- frontend/containers/PostContainer.tsx
- frontend/containers/TimelineContainer.tsx
- frontend/containers/ViewerContainer.tsx
- frontend/stores/modules/ViewerStore.ts
- frontend/stores/modules/index.ts
- frontend/styles/utils/_variables.scss
- frontend/utils/getCoolDate.ts
- textarea에서 포스트 작성시 개행 처리
- 포스트 시간 처리
- 포스트 사용자 누르면 사용자 정보 페이지로 이동
- 포스트 이미지 갯수 제한
- 이미지 클릭하면 뷰어 창 띄우기
- sass lint
>  #121 포스트 에디터 및 뷰잉 개선

- backend/src/routes/follow/follow.controller.ts
- backend/src/routes/follow/index.ts
- backend/src/routes/post/index.ts
- backend/src/routes/post/post.controller.ts
- frontend/api/follow.ts
- frontend/api/post.ts
- frontend/api/user.ts
- frontend/components/Banner/Banner.tsx
- frontend/components/Friend/Friend.stories.tsx
- frontend/components/Friend/FriendItem.scss
- frontend/components/Friend/FriendItem.tsx
- frontend/components/Friend/FriendList.scss
- frontend/components/Friend/FriendList.tsx
- frontend/components/Gallery/Gallery.scss
- frontend/components/Gallery/Gallery.stories.tsx
- frontend/components/Gallery/Gallery.tsx
- frontend/components/Gallery/GalleryPhoto.tsx
- frontend/components/Viewer/Viewer.stories.tsx
- frontend/components/Viewer/Viewer.tsx
- frontend/components/common/Header/Header.tsx
- frontend/containers/BannerContainer.tsx
- frontend/containers/FriendContainer.tsx
- frontend/containers/PictureContainer.tsx
- frontend/containers/TimelineContainer.tsx
- frontend/pages/profile/picture.tsx
- frontend/routes.js
- frontend/stores/modules/PostStore.ts
- 사용자 정보 친구, 사진 보이기
- profile 관련 endpoint에 항상 userId 포함
- storybook fix
> #122 사용자 정보 - 친구, 사진 보이기

- frontend/components/Banner/Banner.tsx
- frontend/components/Editor/Editor.scss
- frontend/components/Editor/Editor.stories.tsx
- frontend/components/Editor/Editor.tsx
- frontend/components/Follow/Follow.tsx
- frontend/components/Friend/FriendItem.tsx
- frontend/components/Gallery/Gallery.scss
- frontend/components/Login/LoginFooter.tsx
- frontend/components/Login/LoginHeader.tsx
- frontend/components/Post/Post.scss
- frontend/components/Post/Post.tsx
- frontend/components/Post/PostCommentEditor.tsx
- frontend/components/Post/PostCommentItem.tsx
- frontend/components/Post/PostGallery.tsx
- frontend/components/common/Button/Button.tsx
- frontend/components/common/Header/Header.scss
- frontend/components/common/Header/Header.tsx
- frontend/components/common/Header/HeaderSearchBar.tsx
- frontend/containers/EditorContainer.tsx
- frontend/stores/modules/PostStore.ts
- 포스트 작성 컴포넌트에 이미지 업로드시 미리보기 컴포넌트가 나타나도록 처리
> #136 이미지 업로드시 미리보기 컴포넌트가 나타나도록 처리

- frontend/components/Post/Post.scss
- frontend/components/Post/Post.tsx
- frontend/components/Post/PostCommentItem.scss
- frontend/components/common/Header/Header.scss
- Post의 content의 태그를 pre로 수정
- 댓글 사용자명과 내용 띄어쓰기하기
- header min-width 준거 제거
- 로그인 안할시 포스트 밑에 border가 안보이도록 처리
> #139 버그 수정
